// DATA GENERATED BY AI

import type { Teacher } from "@/types/teacher";
import type { Student } from "@/types/student";
import { v4 as uuidv4 } from "uuid";
import type { Course } from "@/types/course";

const levels = [
  { id: uuidv4(), levelName: "6ème" },
  { id: uuidv4(), levelName: "5ème" },
  { id: uuidv4(), levelName: "4ème" },
  { id: uuidv4(), levelName: "3ème" },
  { id: uuidv4(), levelName: "2nde" },
  { id: uuidv4(), levelName: "1ère" },
  { id: uuidv4(), levelName: "Terminale" },
];

const groups = [
  { id: uuidv4(), groupName: "A" },
  { id: uuidv4(), groupName: "B" },
  { id: uuidv4(), groupName: "C" },
];

// Étudiants (16)
// @ts-expect-error
export const students: Student[] = [
  { firstName: "Toavina", lastName: "Ranaivo", gender: "Masculin" },
  { firstName: "Fanja", lastName: "Rasoanaivo", gender: "Féminin" },
  { firstName: "Tiana", lastName: "Randria", gender: "Masculin" },
  { firstName: "Mialy", lastName: "Andriamatoa", gender: "Féminin" },
  { firstName: "Hery", lastName: "Rakoto", gender: "Masculin" },
  { firstName: "Soa", lastName: "Ravelomanana", gender: "Féminin" },
  { firstName: "Tsiry", lastName: "Andrianina", gender: "Masculin" },
  { firstName: "Lova", lastName: "Rasoa", gender: "Féminin" },
  { firstName: "Fetra", lastName: "Razanakoto", gender: "Masculin" },
  { firstName: "Ny Aina", lastName: "Raharison", gender: "Féminin" },
  { firstName: "Tsiory", lastName: "Rabe", gender: "Masculin" },
  { firstName: "Sarobidy", lastName: "Rakotondrainibe", gender: "Féminin" },
  { firstName: "Faniry", lastName: "Rafalimanana", gender: "Féminin" },
  { firstName: "Toky", lastName: "Randrianasolo", gender: "Masculin" },
  { firstName: "Zo", lastName: "Ranaivomanana", gender: "Masculin" },
  { firstName: "Nirina", lastName: "Rasoazanany", gender: "Féminin" },
].map((s, i) => ({
  id: uuidv4(),
  ...s,
  birthDate: new Date(2007 + (i % 3), i % 12, (i % 28) + 1),
  email: `${s.firstName.toLowerCase()}.${s.lastName.toLowerCase()}@student.mg`,
  phone: `032${Math.floor(1000000 + Math.random() * 8999999)}`,
  password: "hashed_password",
  address: "Antananarivo, Madagascar",
  phoneNumber: `034${Math.floor(1000000 + Math.random() * 8999999)}`,
  avatar: null,
  role: "STUDENT",
  registrationNumber: `STU${1000 + i}`,
  level: levels[i % levels.length],
  group: groups[i % groups.length],
  createdAt: new Date(),
  updatedAt: new Date(),
}));

// Enseignants (7)
export const teachers: Teacher[] = [
  { firstName: "Rado", lastName: "Andriatsiferana", gender: "Masculin" },
  { firstName: "Hanitra", lastName: "Ravelonandro", gender: "Féminin" },
  { firstName: "Tokiniaina", lastName: "Randrianarisoa", gender: "Masculin" },
  { firstName: "Sitraka", lastName: "Rakotomalala", gender: "Masculin" },
  { firstName: "Vololona", lastName: "Ratsimba", gender: "Féminin" },
  { firstName: "Haja", lastName: "Ranaivomanana", gender: "Masculin" },
  { firstName: "Mamy", lastName: "Rasoanirina", gender: "Féminin" },
].map((t, i) => {
  const teacher: Teacher = {
    userId: uuidv4(),
    ...t,
    birthDate: new Date(1980 + (i % 8), i % 12, (i % 28) + 1),
    email: `${t.firstName.toLowerCase()}.${t.lastName.toLowerCase()}@teacher.mg`,
    password: "hashed_password",
    address: "Antananarivo, Madagascar",
    phoneNumber: `038${Math.floor(1000000 + Math.random() * 8999999)}`,
    avatar: null,
    role: "TEACHER",
    matriculeNumber: `TCH${200 + i}`,
    bio: `Professeur expérimenté en ${[
        "mathématiques",
        "français",
        "physique-chimie",
        "SVT",
        "histoire-géographie",
        "anglais",
        "éducation civique",
      ][i]}. Passionné par l’enseignement.`,
    createdAt: new Date(),
    updatedAt: new Date(),
    courses: [],
    passwordHash: "",
    sex: "MASCULIN"
  };
  return teacher;
});

export const courseTitles = [
  "Mathématiques",
  "Français",
  "Physique-Chimie",
  "Sciences de la Vie et de la Terre",
  "Histoire-Géographie",
  "Anglais",
  "Éducation Civique et Morale",
];

teachers.forEach((teacher, i) => {
  teacher.courses.push({
    id: uuidv4(),
    title: courseTitles[i],
    teacherName: "",
    teacherMatricule: "TCH-203",
    description: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  });
});



export const mockCourses: Course[] = courseTitles.map((c) => {
  const course: Course = {
    id: uuidv4(),
    title: c,
    teacherName: teachers[Math.floor(Math.random() * teachers.length)].firstName,
    createdAt: new Date(2025, 9, 10),
    updatedAt: new Date(2025, 10, 4),
    description: "",
    teacherMatricule: teachers[Math.floor(Math.random() * teachers.length)].matriculeNumber
  };
  return course;
});
