import type { Student } from "@/types/student";
import type { Teacher } from "@/types/teacher";

export const mockTeacher: Teacher = {
  userId: "t1",
  firstName: "Marie",
  lastName: "Lefèvre",
  email: "marie.lefevre@gmail.com",
  password: "hashed_password",
  address: "15 Rue de l'École, Paris",
  phoneNumber: "+33 6 12 34 56 78",
  role: "TEACHER",
  createdAt: new Date("2022-01-05"),
  updatedAt: new Date("2024-04-01"),
  matriculeNumber: "TEA-2023-001",
  bio: "Professeure passionnée par les mathématiques depuis plus de 15 ans.",
  courses: [
    {
      id: "c1",
      title: "Algèbre avancée",
      teacherName: "Hanta",
      teacherMatricule: "TCH-2024-90",
      description: "Experte en mathematiques avancee",
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2024-02-10"),
    },
    {
      id: "c2",
      title: "Analyse mathématique",
      teacherName: "Hanta",
      teacherMatricule: "TCH-2024-90",
      description: "Experte en mathematiques avancee",
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2024-02-10"),
    },
    {
      id: "c3",
      title: "SVT",
      teacherName: "Hanta",
      teacherMatricule: "TCH-2024-90",
      description: "Experte en mathematiques avancee",
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2024-02-10"),
    },
    {
      id: "c4",
      title: "Physique-chimie",
      teacherName: "Hanta",
      teacherMatricule: "TCH-2024-90",
      description: "Experte en mathematiques avancee",
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2024-02-10"),
    },
  ],
  sex: "FEMININ",
  passwordHash: "",
  birthDate: new Date(1990, 4, 12),
  avatar: "https://randomuser.me/api/portraits/women/45.jpg",
};

export const mockStudent: Student = {
  userId: "s1",
  firstName: "Mickael",
  lastName: "RANDRIANIRINA",
  email: "lucas.dupont@example.com",
  password: "hashed_password",
  address: "10 Rue des Fleurs, Lyon",
  phoneNumber: "+33 7 12 34 56 78",
  role: "STUDENT",
  createdAt: new Date("2023-09-15"),
  updatedAt: new Date(),
  registrationNumber: "STU-2023-104",
  level: {
    id: "l1",
    name: "Terminale S",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  group: {
    id: "g1",
    name: "Groupe A",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  sex: "MASCULIN",
  passwordHash: "",
  birthDate: new Date(2009, 10, 20),
  avatar: "https://randomuser.me/api/portraits/men/1.jpg",
};
